package com.jittr.android.gamemanager.games;

//import java.io.Serializable;

import android.os.Parcel;
import android.os.Parcelable;

import com.jittr.android.gamemanager.baseTablePojo;

/* Standardize field names throughout including from XML dtd */
/* id = id,
 * name = title
 * type = type
 * complete = complete 
 * 
 */
public class Game extends baseTablePojo implements Parcelable {
	
	/**
	 * Generated by Eclipse
	 */
   // public static final Creator<Game> CREATOR;
	//private static final long serialVersionUID = 5527258407135652423L;
	
	private long id;  //unique
	private String title;
	private String description;
	private String eventName;
	private String eventDate;
	private int numberSubscribers;
	private String type;
	private boolean complete;
    private int visibility;
   
    public Game() {
    	super();
    }
    
    public static final Parcelable.Creator<Game> CREATOR
    = new Parcelable.Creator<Game>() {

   	
    public Game createFromParcel(Parcel in) {
        return new Game(in);
     } //createFromParcel

	public Game[] newArray(int arg0) {
		// TODO Auto-generated method stub
		return null;
	}
    
     };

     private Game(Parcel in) {
    	 readFromParcel(in);
     	//name = "this is a test";
     }
	public void readFromParcel(Parcel in) {
		// TODO Auto-generated method stub
	   id = in.readLong();
	   title = in.readString();
	   type = in.readString();
	   //complete=in.readBooleanArray(null);
	   visibility=in.readInt();
	   this.setCreatedDate(in.readString());
	}
	public Game(String taskName) {
		title = taskName;
	}

	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getEventName() {
		return eventName;
	}
	public void setEventName(String eventName) {
		this.eventName = eventName;
	}
	public String getEventDate() {
		return eventDate;
	}
	public void setEventDate(String eventDate) {
		this.eventDate = eventDate;
	}
	public int getNumberSubscribers() {
		return numberSubscribers;
	}
	public void setNumberSubscribers(int numberSubscribers) {
		this.numberSubscribers = numberSubscribers;
	}
	public void setId(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}

	public void setName(String name) {
		this.title = name;
	}

	public String getName() {
		return title;
	}
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setComplete(boolean complete) {
		this.complete = complete;
	}

	public boolean isComplete() {
		return complete;
	}

	public int getVisibility() {
		return visibility;
	}

	public void setVisibility(int visibility) {
		this.visibility = visibility;
	}
	public void toggleComplete() {
		complete = !complete;
	}

	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	public void writeToParcel(Parcel in, int arg1) {
		
		in.writeLong(this.getId());
	    in.writeString(this.getName());	
	}

	
	@Override
	public String toString() {
		return "Game [complete=" + complete + ", description=" + description
				+ ", eventDate=" + eventDate + ", id=" + id
				+ ", numberSubscribers=" + numberSubscribers + ", title="
				+ title + ", type=" + type + ", visibility=" + visibility
				+ ", getCreatedDate()=" + getCreatedDate()
				+ ", getModifiedDate()=" + getModifiedDate() + "]";
	}


}
